### ISSUE TITLE
Detect if PWA is added to home screen

### ISSUE THREAD

**Issue by carromeu** [duskload/mobile-device-detect#1]
Hi team,

First, congrats for this tool... is very useful!!

Has any way to detect if PWA has been installed (added to home screen)? I am using this package to detect iOS and presents to user the steps to add to home screen (like Android). But, after the user add to home screen, my code still present this option.

I suggest a attribute like "inHomeScreen" to differ access in browser from access by icon in home screen.

Thanks!

**Comment by carromeu** [comment]
I found this to help:
https://stackoverflow.com/questions/51735869/check-if-user-has-already-installed-pwa-to-homescreen-on-chrome

**Comment by duskload** [comment]
@carromeu, I don't see how is it related to this application?

**Comment by duskload** [comment]
Detecting if PWA has been installed is beyond the scope of this application.
