### ISSUE TITLE
Doesn't recognize Edge Chromium

### ISSUE THREAD

**Issue by joaofbvieira** [duskload/mobile-device-detect#39]
Value of "isEdge" is false when using new Edge Chromium.
This is my navigation.userAgent:
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.77"

I'm using Edge Chromium version 81.0.416.77.

**Comment by duskload** [comment]
@joaofbvieira fix is available in a next release. You can update package version and try it.
